name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      
      - name: Build package
        run: |
          uv build
      
      - name: Verify package
        run: |
          uv run --with dist/*.whl --no-project -- python -c "import eoir; print(f'EOIR version: {eoir.__version__}')"
          uv run --with dist/*.whl --no-project -- eoir --help
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
